---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  # Minimum supported Rust version (MSRV)
  ACTION_MSRV_TOOLCHAIN: 1.60.0
  # Pinned toolchain for linting
  ACTION_LINTS_TOOLCHAIN: 1.60.0

jobs:
  build-tests:
    name: "Build Integration Test Data"
    runs-on: ubuntu-latest
    container: registry.ci.openshift.org/coreos/fcos-buildroot:testing-devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # https://github.com/actions/checkout/issues/760
      - name: Mark git checkout as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Build
        run: make -C tests/kolainst && make -C tests/kolainst install DESTDIR=$(pwd)/install && tar -C install -czf tests.tar .
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: tests.tar
          path: tests.tar
